name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Check black
        uses: psf/black@stable
        with:
          options: "--check --verbose --line-length 140"
          src: "./orm_study"
          version: "~= 22.0"

      - name: Check flake8
        uses: py-actions/flake8@v2
        with:
          path: "./orm_study"
